import { Mitr } from 'next/font/google'
import './globals.css'
const mitr = Mitr({ weight: ["200", "400", "600"], subsets: ['thai'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className={mitr.className}>
        {children} </body>
    </html>

  )
}
